from .text_file import TextFile, new_text_file
from .exploratory_search import ExploratorySearchResult, new_exploratory_search_result, exploratory_search_by_word
from .comparison import CompareQvsKsResult, new_compare_q_vs_ks_result, compare_q_vs_k
from .consistency import ConsistencyResult, new_consistency_result, consistency_k_vs_k